global using System.Security.Claims;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Authorization;
global using ServiceAbstraction;
global using Shared.DataTransferObjects.IdentityDtos;
global using Shared.DataTransferObjects.BasketModuleDto;
global using Shared.DataTransferObjects.OrderDtos;
global using Shared;
global using Shared.DataTransferObjects.ProductModuleDto;
